### ISSUE TITLE
Fix Hover Issues and Feature Visibility in Featured Pumpkins Section for Hacktoberfest

### ISSUE THREAD

**Issue by solanki03** [OpenCodeChicago/Midwest-Pumpkins#100]
Our featured pumpkins section is experiencing hover problems, and the listed features are too large. Additionally, the features of each card aren't properly visible on mobile devices. I would like to address these issues. Could you please assign it to me for Hacktoberfest?

**Comment by vivek1842** [comment]
@Alexandrbig1 is this issue assigned to someone? If not, then I would like to work on it

**Comment by christalchronicles** [comment]
@solanki03 @vivek1842 This issue is being worked on as part of another opened issue: [Features Section Design #24](https://github.com/OpenCodeChicago/Midwest-Pumpkins/issues/24)

**Comment by vivek1842** [comment]
@christalchronicles ok no problem .. also fix the hover issue of featured section... It's still not aligned properly

**Comment by solanki03** [comment]
@christalchronicles I went through Issue #24, which resolves the responsiveness problem. However, the list mentioned in the card is not visible on mobile devices. I have attached a video regarding this issue.

![image](https://github.com/user-attachments/assets/3008b1c7-750a-42e6-8449-ab2b523e9b1d)

https://github.com/user-attachments/assets/1aa290ea-9a96-4223-b36b-7057ada2577b
