### ISSUE TITLE
Header for Desktop Device

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#21]
**Description**:
The desktop version of the header should include the company logo, a navigation menu, and a list of links to the company’s social media profiles.

**Requirements**:
1. **Logo**:
    - Place the company logo in the header, positioned on the left side.

2. **Navigation Menu**:
    - Implement the navigation menu to the right of the logo, displaying the main sections of the website (e.g., "Home," "About," "Best 
    pumpkins").
    - Ensure the navigation menu is fully responsive and accessible on larger screens.

3. **Social Media Links**:
    - The social media links should be implemented as a list (`<ul>`) where each item contains an `<a>` tag.
    - Each link should open the corresponding social media platform in a new tab.
    - Use SVG format for the social media icons, ensuring they are visually appealing and consistent in size and style.
    - Position the social media icons on the middles of the header, aligned with the navigation menu.

**Additional Considerations**:
- Ensure the header is fixed at the top of the page on scroll (sticky header).
- The design should be clean, with sufficient spacing between the logo, navigation menu, and social media links for an uncluttered 
look.
- Test the header across multiple desktop resolutions to ensure proper responsiveness and layout.

**Social Links**:
- **GitHub**: https://github.com/OpenCodeChicago
- **YouTube**: https://www.youtube.com/@AlexSmaginDev
- **LinkedIn**: https://www.linkedin.com/company/open-code-chicago
- **X - Twitter**: https://x.com/alexsmagin29
- **Facebook**: https://www.facebook.com/profile.php?id=61565627819350

**Comment by shubhamsharma9199** [comment]
@Alexandrbig1 Can you assign this work to me and label it as 'Hacktoberfest Accepted

**Comment by Alexandrbig1** [comment]
Hi, yeah, after today's meeting(at 12pm CST) i'll manage it

**Comment by Alexandrbig1** [comment]
@tanvi4248 this is your new task 🚀

**Comment by shubhamsharma9199** [comment]
![Screenshot 2024-10-12 172126](https://github.com/user-attachments/assets/73d3e8fe-3b2e-41e2-822a-79323703fd44)
@Alexandrbig1 
Here is the final result of the website design. The layout is complete, except for the missing company logo. If you have any suggestions or want to make any changes, feel free to let me know!"

Let me know if you need further adjustments!

**Comment by Alexandrbig1** [comment]
@shubhamsharma9199 you probably don't understand how to contribute to our project. Please, read carefully documentation, as well you can watch video on YouTube, to understand what each of developer should do. Thank you, if you'll still have any question, please ask me in our open Discussions for this project. Thank you

**Comment by tanvi4248** [comment]
I'm doing this task or not ?

**Comment by Alexandrbig1** [comment]
@tanvi4248 yes, you assigned, read my comment before ☺️

**Comment by Alexandrbig1** [comment]
@tanvi4248 how is your progress? there still minor issues need to fix in header for desktop device.

**Comment by tanvi4248** [comment]
Can you mention issues so I can fix it.

**Comment by Alexandrbig1** [comment]
@tanvi4248 you can open design and our website, and see the difference. At least what I'm see right away, even without checking it, that the color for links, they all read. also the social icons is not in right place...also hover for social icons is not with transition...etc, Please test it as it's your task to be sure that is looks and works well.Thank you

**Comment by tanvi4248** [comment]
hello @Alexandrbig1  somebody changed my desktop header css. there is some css which is i didnt change

**Comment by tanvi4248** [comment]
https://github.com/OpenCodeChicago/Midwest-Pumpkins/pull/119/files#diff-1785483a33076832eb40cc3dc29b03cca0592cd69e9e03f6da7c36ba5e308a2e  Here is the link somebody changed header css for desktop

**Comment by Alexandrbig1** [comment]
@tanvi4248 great work Tanvi!
