### ISSUE TITLE
Hero Section Implementation

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#22]
1. **Main Title**
    - Update the text in the Hero section to display "Best Pumpkins in the Midwest" as the main title. Ensure it stands out with 
    appropriate styling and font size to capture users' attention.

2. **Buy Now Button**
    - Implement the "Buy Now" button functionality:
        - When clicked, it should open a modal window titled "Buy Now."

3. **Top Sellers Button**
    - Create a button labeled "Top Sellers":
    - This button should function as an anchor link, smoothly scrolling the page to the "Top Sellers" section when clicked.
    - Verify that the button is visually distinct and encourages users to explore the top-selling products.

**Additional Considerations**
    - Styling: Ensure that all buttons are styled consistently with the overall theme of the website, including hover effects and 
    transitions.
    - Accessibility: Implement proper ARIA labels for the buttons to enhance accessibility for all users.
    - Testing: After implementing these features, conduct thorough testing to ensure all interactions work as intended across different 
    devices and screen sizes.

**Comment by Alexandrbig1** [comment]
@tanvi4248 the section is still in progress, right?

**Comment by tanvi4248** [comment]
everything is done but i have to add buynow button click javascript but i think buy now popup modal is still remaining

**Comment by Alexandrbig1** [comment]
@tanvi4248 1st - it's not responsive at all. 2nd add hover effect for 2nd button as well, all buttons must be interactive for user.

**Comment by Alexandrbig1** [comment]
![tanvi1](https://github.com/user-attachments/assets/615d38e6-b24f-4b35-ae0a-40b0c7389b88)
![tanvi2](https://github.com/user-attachments/assets/e9233702-a353-4de1-ab5c-fdf2425f5670)

**Comment by Alexandrbig1** [comment]
3rd also check the spaces between content and end of image

**Comment by tanvi4248** [comment]
I thought someone else doing responsive. Ok I will do responsive tomorrow
for all devices .

**Comment by Alexandrbig1** [comment]
@tanvi4248 yeah, it's little bit confusing. The responsive task for another contributor is to build a responsive main container, a layout for entire project. But for each section everyone's is doing own responsive layout ☺️

**Comment by tanvi4248** [comment]
ok got it

**Comment by Alexandrbig1** [comment]
@tanvi4248 great work Tanvi!
