### ISSUE TITLE
Top Sellers Section Setup

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#25]
1. **Section Header**

- Implement the header text "TOP SELLERS" as a prominent section title.
- Ensure the title is styled to align with the overall theme of the page.

2. **Content Images List**

- Create a list of top-selling products using an unordered list (`<ul>`).
- Each list item (`<li>`) should include:
    - A content image representing the top seller.

3. **Grid Layout**

- Arrange the list items in a responsive grid layout to provide an appealing presentation of the top sellers.
- Use CSS Grid or Flexbox for layout management to ensure responsiveness across various devices.

4. **“Buy Now” Button**

- Include a "Buy now" button for each top-selling item.
- Implement functionality so that clicking the button opens the "Buy now" modal window.
- Ensure that the button is styled consistently with other buttons in the project.

5. **Testing**

- Test the Top Sellers section across different devices and browsers to ensure that images load correctly and that the layout is responsive.
- Verify that the "Buy now" button opens the modal as expected.

**Comment by 19purva** [comment]
Is the issue still open? Can I contribute?

**Comment by Alexandrbig1** [comment]
@19purva this issue is assigned for another team member. You can see on our Projects Kanban board for Midwest Pumpkin and find the task that still is open and let me know in which you want to contribute

**Comment by a-woodworth** [comment]
Can I contribute to this section? Would like to rework html to create list for images and add styles.
