### ISSUE TITLE
User Reviews Integration

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#26]
1. **Section Header**

- Implement the header text "Pumpkins People Love!" as the main title of the user reviews section.
- Style the title to ensure it is visually distinct and aligns with the overall design theme of the website.

2. **Customer Reviews Slider**

- Integrate a review slider that showcases testimonials from customers who have purchased the pumpkins.
- Ensure that the slider includes the following features:
    - Automatic sliding functionality to display multiple reviews.
    - Manual navigation controls (previous and next buttons) for user interaction.

3. **Pagination Markers**

- Use pagination markers at the bottom of the slider to indicate the current review being displayed.
- If using a slider library, the pagination markers will be generated automatically. Ensure that any necessary styling is applied to match the project's design aesthetic.

4. **Leave a Review Button**

- Include a "Leave a Review" button prominently within the section.
- Implement functionality so that clicking the button opens the modal window titled "Leave a review about our pumpkins."
- Ensure that the button's styling is consistent with the other buttons used throughout the project.

5. **Testing**

- Test the user reviews slider across different devices and screen sizes to ensure proper functionality and responsiveness.
- Verify that the modal opens correctly and that users can easily leave their reviews.

**Comment by SreyaSudheeran** [comment]
I would like to work on this issue. Please assign me this issue

**Comment by Alexandrbig1** [comment]
@SreyaSudheeran ok got it, please read carefully documentation, also watch video to understand how to contribute to our project as well as read the Contributing.md file.
Assigned, waiting PR's from you

**Comment by Alexandrbig1** [comment]
@SreyaSudheeran great work Sreya!
