### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#28]
1. **Company Slogan**

- Include the company slogan prominently in the footer.
- Ensure the slogan is styled to be visually distinct and harmonizes with the overall footer design.

2. **Contact Information**

- Display the company's contact number and email address in the footer.
- Implement the contact number using a tel: protocol link for easy dialing on mobile devices.
- Implement the email address using a mailto: protocol link to allow users to send emails directly from the footer.

3. **Social Media Links**

- Create a list of social media links for the company, utilizing an unordered list (`<ul>`).
- Each list item should contain a link that opens the respective social media platform in a new tab.
- Use SVG icons for each social media platform for a clean and modern look. Ensure the icons are appropriately sized and styled.

4. **Anchor Links**

- Include a list of anchor links to different sections of the website, implemented as another unordered list (`<ul>`).
- Each list item should link to specific sections within the site, enhancing user navigation.

5. **Styling and Responsiveness**

- Style the footer to be visually appealing, ensuring it integrates seamlessly with the overall design of the website.
- Test the footer on various screen sizes to ensure it remains responsive and user-friendly.

**Social Links**:
- **GitHub**: https://github.com/OpenCodeChicago
- **YouTube**: https://www.youtube.com/@AlexSmaginDev
- **LinkedIn**: https://www.linkedin.com/company/open-code-chicago
- **X - Twitter**: https://x.com/alexsmagin29
- **Facebook**: https://www.facebook.com/profile.php?id=61565627819350

**Comment by shubhamsharma9199** [comment]
@Alexandrbig1 Can you assign this work to me and label it as 'Hacktoberfest Accepted

**Comment by Alexandrbig1** [comment]
You've already asked about header. Or you want to make 2 sections? Let me see after today's meeting, how many people will participate

**Comment by shubhamsharma9199** [comment]
@Alexandrbig1 If both tasks are assigned to me, I’ll work on both the header and the footer section. Additionally, I’m interested in working on the footer project as well, if it's available.

**Comment by shubhamsharma9199** [comment]
@Alexandrbig1 I’ve already completed half of the work on this project and I’m ready to handle the rest. If both the header and the footer section are assigned to me, I’m confident I can manage both. Additionally, I’d like to express my interest in taking on the footer project as well if that becomes available. I’m committed to delivering all tasks effectively and on time."

**Comment by Alexandrbig1** [comment]
@shubhamsharma9199 I assigned you on header section. Footer is currently under Kim @bibimbop123

**Comment by Alexandrbig1** [comment]
@shubhamsharma9199 That's great! Even the project will start at 1st of October you did a great job! Keep it up! Right now it's just the 'close modal functionality' is opened task. Let's see how it goes, let's everyone finish their task and then we see if in any section there need to be adjustment. Thank you! Waiting your pull requests from 1st of October!

**Comment by sakshitawde** [comment]
"Hi 👋🏻 @Alexandrbig1, I've completed the changes for the footer design. Could you please take a moment to review my work? Your feedback would be greatly appreciated!"

**Comment by Alexandrbig1** [comment]
@sakshitawde your section is header. The footer is for another team member. Please check our Projects Kanban board: https://github.com/orgs/OpenCodeChicago/projects/1

**Comment by Alexandrbig1** [comment]
@sakshitawde and also, on html - no need to create !Doctype declaration. as this component is partial and it's loaded to the index.html file already.

**Comment by Alexandrbig1** [comment]
@sakshitawde also, follow BEM model of naming classes, for example if you working on your section header, the main wrapper class is header, and the everything what inside name like this 'header-title, or header-nav, or header-nav-links' etc.

**Comment by mrunaliiii** [comment]
i would like to work on this issue . can you assign this issue to me ?

**Comment by Alexandrbig1** [comment]
@mrunaliiii got it, I'll assign you, and wait at least some changes by two days. Please read carefully documentation, also you can watch YouTube video to understand how to contribute.Feel free to ask questions on Discussions tab for this project. waiting for your work, thank you!

**Comment by Alexandrbig1** [comment]
@mrunaliiii any updates on your task?

**Comment by a-woodworth** [comment]
@Alexandrbig1   I can work on this task

**Comment by Alexandrbig1** [comment]
@a-woodworth great! Assigned!

**Comment by Alexandrbig1** [comment]
@a-woodworth hi Amy, how's footer is going?

**Comment by Alexandrbig1** [comment]
@a-woodworth great work Amy!
