### ISSUE TITLE
Leave a Review Pop-Up

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#30]
1. Modal Title

- The modal window should have a title that displays “LEAVE A REVIEW ABOUT OUR PUMPKINS” prominently at the top.

2. Form Elements

- Include a form within the modal that contains the following `<input>` elements:
    - Name: A text input for the user's name, with validation to ensure at least two characters using the `pattern` attribute.
    - Email: An email input for the user's email address, ensuring proper email formatting with the `pattern` attribute.
    - Phone Number: A text input for the user's phone number, using a pattern to validate valid phone number formats.
    - Message: A text area for users to leave their review or feedback.
- Implement minimum validation for each input field using the `pattern` attribute to ensure users provide valid data:
    - For the name, the pattern could require at least two characters.
    - For the email, use a standard email format pattern.
    - For the phone number, implement a pattern that allows only valid phone number formats (e.g., 10 digits).

3. Submit Button

- Include a “Submit” button of type `submit` that processes the form data.
- When the button is clicked, the modal should close, indicating to the user that their review has been submitted.

**Comment by Mayuphapale** [comment]
I would like to work on this issue . can you assign this issue to me ?

**Comment by Alexandrbig1** [comment]
@Mayuphapale hi, yes you can. Please read carefully documentation, also you can watch video of how to contribute as well as read Contributing.md file. You assigned for this task, I'm waiting for your PR's. Thank you

**Comment by Alexandrbig1** [comment]
@Mayuphapale any updates on your task?

**Comment by Alexandrbig1** [comment]
@a-woodworth Amy, do you want to put your hands on this task and finish it?

**Comment by a-woodworth** [comment]
@Alexandrbig1 I can do it, but can't get to it until this weekend.

**Comment by Alexandrbig1** [comment]
@a-woodworth that's ok, if no one is start till that, we still have a week to finish our project.

**Comment by Alexandrbig1** [comment]
@a-woodworth great work Amy!
