### ISSUE TITLE
Subscription Pop-Up

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#31]
1. **Modal Title**
The modal window should have a title that displays “EXPLORE OUR PUMPKINS FIRST!!” prominently at the top.

2. **Form Elements**
Include a form within the modal that contains the following `<input>` element:
Email: An email input for the user's email address, ensuring proper email formatting. Implement minimum validation using the `pattern` attribute to ensure users provide a valid email format.

3. **Submit Button**
Include a “Submit” button of type `submit` that processes the form data.
When the button is clicked, the modal should close, indicating to the user that their subscription has been submitted successfully.

**Comment by Queen-2022-11** [comment]
Is the issue still open? Can I contribute?

**Comment by Alexandrbig1** [comment]
Yes, the project isn't started yet, it will begin at 1st of October, but today 28th of September we starting project with meeting at 12pm CST, please be welcome to join

**Comment by Alexandrbig1** [comment]
@DanielDunevant any updates on your task?

**Comment by DanielDunevant** [comment]
This one is done right?

**Comment by Alexandrbig1** [comment]
@DanielDunevant There high priorite bug, when you open modal pop-up, and click 'ESC' the modal pop-up is not closing and the x-button is disappearing. And also some issues with styling. I will provide you images from our design layout and how it's look like in our website right now. But you can verify when you testing your task from [Figma](https://www.figma.com/design/6keWgZp7kRbn3CLMt3rWqp/Midwest-Pumpkins?node-id=0-1&t=fmI04OejcL0nLtGh-1) 

**mobile figma layout**
<img width="340" alt="dan1" src="https://github.com/user-attachments/assets/6a363ca7-56be-4f25-ac3d-1114e7b0a036">

**current website mobile device**
<img width="181" alt="dan2" src="https://github.com/user-attachments/assets/eff0d327-6667-46e6-b877-d52c08e7b88e">

**tablet figma layout**
<img width="394" alt="dan3" src="https://github.com/user-attachments/assets/90e0c4e6-d5bc-4b0f-81c1-cd3ec0ee5bd1">

**current website tablet device**
<img width="325" alt="dan4" src="https://github.com/user-attachments/assets/a850e920-1d3b-4e3e-ac4c-7512acf2e86e">

**current website desktop device**
<img width="833" alt="dan5" src="https://github.com/user-attachments/assets/e4cc35cb-cb01-454a-86ef-0d57fd54cb34">

**desktop figma layout**
<img width="698" alt="dan6" src="https://github.com/user-attachments/assets/b0065fae-21b9-4683-bbeb-40015362bf2c">

**Comment by DanielDunevant** [comment]
I had it as depicted. I noticed this when I was making my most recent change. I'm not sure when down the line they were changed. I will change them back to as it was in the figma. Thanks!

**Comment by Alexandrbig1** [comment]
@DanielDunevant great work Daniel!
