### ISSUE TITLE
Close Window Implementation

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#39]
1. **Task Description**

- Implement a close functionality for each pop-up modal: "Buy Now", "Leave a Review", and "Subscribe".

2. **Implementation Steps**

- Add a close button (e.g., an "X" icon) within each modal window.
- Implement an event listener for the close button to hide the modal when clicked:
    - Use JavaScript to toggle the visibility of the modal.
    - Ensure that clicking outside the modal area and 'Esc' button also closes the modal.
    - Optionally, add a transition effect for a smoother user experience when the modal opens and closes.

3. **Verification**

- Test each modal to ensure:
    - The close button effectively hides the modal.
    - Clicking outside the modal and 'Esc' button also closes it.
    - The close functionality works without errors in the console.

**Comment by sakshitawde** [comment]
@Alexandrbig1 can you explain this issue

**Comment by Alexandrbig1** [comment]
@sakshitawde check the description for this issue, please. This is a close button for all pop-up windows

**Comment by blunterdecosta123** [comment]
Hi @Alexandrbig1 can you assign me this issue i would like to work on it

**Comment by Alexandrbig1** [comment]
@blunterdecosta123 yes sure. Thank you

**Comment by Alexandrbig1** [comment]
@DanielDunevant Daniel, do you want to check all `X - buttons` that must close the pop-ups windows in our project?

**Comment by DanielDunevant** [comment]
@Alexandrbig1  I'd be happy to!

**Comment by Alexandrbig1** [comment]
@DanielDunevant great work Daniel!
