### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#40]
1. **Task Description**

- Add a favicon to the webpage to enhance branding and improve user experience.

2. **Implementation Steps**
- Create or obtain a favicon image in `.ico` format.
- Place the favicon file in the `public` directory of the project.
- Link the favicon in the <head> section of the index.html file.
- Ensure the favicon displays correctly across different browsers and devices.

3. **Verification**

- After implementation, check that the favicon appears in the browser tab when the webpage is loaded.

**Comment by blunterdecosta123** [comment]
Hey @Alexandrbig1  can you assign me this issue i would like to work on it.

**Comment by Alexandrbig1** [comment]
@blunterdecosta123 this task is already assigned for another contributor. Please find another task which is still open

**Comment by bawsepap** [comment]
added the favicon to the page

**Comment by Alexandrbig1** [comment]
@bawsepap you need create a PR, to our project that I can accept it.
