### ISSUE TITLE
Burger Menu for Mobile and Tablet Devices

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#41]
**Description**:
The mobile and tablet versions of the navigation menu need to be implemented as a responsive, sliding sidebar (burger menu). The menu should be fixed, occupying the full height of the viewport, and include anchor links to navigate to specific sections of the page.

**Requirements**:

1. **Navigation Menu**:

    - On mobile and tablet devices, the navigation menu should appear as a sliding sidebar (burger menu) when toggled.
    - The menu should be fixed, meaning it remains visible even while scrolling.
    - The height of the menu must adjust dynamically to match the viewport height (100vh).
    - Anchor links in the menu should smoothly scroll to the corresponding sections of the page (e.g., "Home," "About," "Best 
    pumpkins," "Top sellers").

2. **Social Media Links**:

    - Social media links should be structured as a list (`<ul>`), with each list item containing an `<a>` tag that opens the 
    corresponding social media site in a new tab.
    - Use SVG icons for each social media platform (e.g., GitHub, YouTube, Twitter). Ensure these icons are well-aligned and visually 
    consistent.
    - The social media links should be placed in the burger menu below the main navigation links.

**Additional Considerations:**

- Ensure the burger menu has smooth opening/closing animations for better user experience.
- The toggle button for the burger menu should be intuitive, typically represented by a three-bar (hamburger) icon.
- Test the implementation on various screen sizes to ensure responsiveness and proper functionality on mobile and tablet devices.

**Comment by 19purva** [comment]
@Alexandrbig1  can you describe me issue ?

**Comment by Alexandrbig1** [comment]
Yes, of course. I hope you checked the Figma layout: https://www.figma.com/design/6keWgZp7kRbn3CLMt3rWqp/Midwest-Pumpkins?node-id=0-1&t=kqGSD5fWaT5tQLTc-1

There you will find a mobile and tablet devices that need to have a burger menu. means that @media(max-width: 1440) the burger icon must be visible, and the nav links is hidden. Once you click on a Burger Menu icon the menu overlay must be transition smoothly from side with visible content on it.

**Comment by 19purva** [comment]
@Alexandrbig1 can you assign me this issue to me?

**Comment by Alexandrbig1** [comment]
Yes, of course! But please, to participate on Hacktoberfest2024 start creating pull requests after 1st of October.

**Comment by Alexandrbig1** [comment]
And also I will add description now for this task

**Comment by Alexandrbig1** [comment]
Also when you'll create an pull request, add descriptive commit and label 'hacktoberfest-accepted'

**Comment by Alexandrbig1** [comment]
@19purva all description is added

**Comment by Virat-Shrimali** [comment]
@Alexandrbig1 can you assign me this issue under hacktoberfest 2024

**Comment by Alexandrbig1** [comment]
@Virat-Shrimali this task is already assigned for another team member, please find another task. Thank you!

**Comment by 19purva** [comment]
i am not able to do pull request, can you guide me how to do pull  request

**Comment by Alexandrbig1** [comment]
@19purva check this video, I'm telling how to contribute to the project, and how to create PR 🔗: https://www.youtube.com/watch?v=1BvBKGzrw4w&t=353s

If you'll still have a question after, let me know

**Comment by 19purva** [comment]
i watched complete video,and follow same procedure still i got error message , permission denied to 19purva,can you provide me steps so , i will get idea how to resolve error and what actually it is

**Comment by Alexandrbig1** [comment]
@19purva all the steps is in video mention. You can back to the video to check once more. Also there a Contributing.md file where provided each of step, you also can check once more.
But yes, here is steps for you:
1. fork the repo (to keep this repo in your profile, and show others that you was contributing on this project;
2. `git clone 'copy htttps link'` to the place in your local machine. CLONE our team project, not yours;
3. open this project;
4. make changes;
5. when you ready to create PR, fetch last updates with `git pull` command;
6. create your own branch `git checkout -b 'your_project_name'`;
7. then write commands `git add .` will add all changes that you made, then `git commit -m "initial commit, what you have done'`;
8. `git push origin 'your branch name'` will push your changes;
9. open repository, and you'll see 'create pull request' or 'review pull request';
10. add me as a reviewer, check what issue you working on, assign me, and create pull request.

**Comment by a-woodworth** [comment]
I'd like to work on this burger menu task as part of hacktoberfest.

**Comment by Alexandrbig1** [comment]
@a-woodworth got it, assigned. Waiting your PR's

**Comment by Alexandrbig1** [comment]
@a-woodworth great work Amy!
