### ISSUE TITLE
Theme Switching Tasks

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#45]
1. **Implement Theme Toggle**
    - Create a toggle switch to allow users to switch between light and dark themes.
    - Ensure that the toggle is easily accessible in the navigation bar or header.

2. **CSS Variables**
    - Utilize CSS variables to define color schemes for both light and dark themes, ensuring that all elements on the page adapt based on the selected theme.
    - Examples of variables to include:
        - Background color
        - Text color
        - Link color
        - Button styles

3. **Persist User Preference**
    - Use local storage to save the user's theme preference so that it persists across page reloads and sessions.
    - Implement logic to check local storage and apply the correct theme on initial load.

4. **Responsive Design**
    - Ensure the theme toggle works seamlessly across all devices and screen sizes, maintaining usability in both light and dark 
    modes.

5. **Testing**
    - Test the theme switching functionality in various browsers to ensure compatibility and check for any visual inconsistencies.

**Comment by rohitgargRG** [comment]
@Alexandrbig1 i would like to work on this issue , please assign this issue to me under hacktoberest label.

**Comment by Alexandrbig1** [comment]
@rohitgargRG got it. Assigned this task for you. Please read carefully our documentation of this project. Also you can watch video to understand how to contribute to our project. Waiting your PR's

**Comment by Lakshita-Kumawat** [comment]
@Alexandrbig1 i would like to complete this task. Please give me a chance

**Comment by Alexandrbig1** [comment]
@Lakshita-Kumawat got it, you can start if you'll make it faster then Rohit you can make a PR. But, you still have `responsive layout` issue, please finish it first.

**Comment by Lakshita-Kumawat** [comment]
@Alexandrbig1 ok

**Comment by Alexandrbig1** [comment]
@Lakshita-Kumawat any updates about this task?

**Comment by Lakshita-Kumawat** [comment]
@Alexandrbig1 i have done it and send a pr but only the colors for the dark theme is remaining because i am not good at choosing colors😅. Else all the work is done

**Comment by Alexandrbig1** [comment]
@LinukaAr great work! 🚀
