### ISSUE TITLE
Notification Implementation for Pop-Up Windows

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#46]
1. **Task Overview**

- Implement a notification system for the following modal windows: “Buy Now,” “Subscribe,” and “Leave a Review.” The notifications should inform users of successful actions upon form submission.

2. **User Notifications**

- For each modal, add notifications that trigger when the user clicks the submit button. These notifications will confirm the action taken:
    - **Buy Now Modal**: Notify the user with a message like "Your order has been successfully placed!" upon submission.
    - **Subscribe Modal**: Notify the user with a message like "Thank you for subscribing! Stay tuned for updates!"
    - **Leave a Review Modal**: Notify the user with a message like "Thank you for your review! We appreciate your feedback!"

3. **Implementation Steps**

- Choose a JavaScript notification library (e.g., SweetAlert, Noty, or Toastr) to handle notifications.
- Ensure each notification appears clearly and is styled to match the overall design of the website.
- Test the notifications for responsiveness and visibility across different devices and browsers.

**Comment by Queen-2022-11** [comment]
can you assign me this issue

**Comment by Alexandrbig1** [comment]
@Queen-2022-11 yes, sure, thank you

**Comment by Queen-2022-11** [comment]
remote: Permission to OpenCodeChicago/Midwest-Pumpkins.git denied to Queen-2022-11.
fatal: unable to access 'https://github.com/OpenCodeChicago/Midwest-Pumpkins.git/': The requested URL returned error: 403 
is there any other way to do pull request
can you guide me

**Comment by Alexandrbig1** [comment]
@Queen-2022-11 check this video, I'm telling how to contribute to the project, and how to create PR 🔗: https://www.youtube.com/watch?v=1BvBKGzrw4w&t=353s

If you'll still have a question after, let me know

**Comment by Queen-2022-11** [comment]
I followed this video, but the issue still persists

**Comment by Alexandrbig1** [comment]
@Queen-2022-11 all the steps is in video mention. You can back to the video to check once more. Also there a Contributing.md file where provided each of step, you also can check once more.

But yes, here is steps for you:
1. fork the repo (to keep this repo in your profile, and show others that you was contributing on this project;
2. `git clone 'copy htttps link'` to the place in your local machine. CLONE our team project, not yours;
3. open this project;
4. make changes;
5. when you ready to create PR, fetch last updates with `git pull` command;
6. create your own branch `git checkout -b 'your_project_name'`;
7. then write commands `git add .` will add all changes that you made, then `git commit -m "initial commit, what you have done'`;
8. `git push origin 'your branch name'` will push your changes;
9. open repository, and you'll see 'create pull request' or 'review pull request';
10. add me as a reviewer, check what issue you working on, assign me, and create pull request.

**Comment by vivek1842** [comment]
Assign me this issue.. I'll implement this

**Comment by Alexandrbig1** [comment]
@vivek1842 hi, alright. Please read carefully documentation, also you can watch video of how to contribute as well as read Contributing.md file. You assigned for this task, I'm waiting for your PR's. Thank you

**Comment by Alexandrbig1** [comment]
@vivek1842 great work Vivek!
