### ISSUE TITLE
Scroll Up Button Implementation

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#49]
**Description**:
Implement a “Scroll Up” button that appears after the user has scrolled down 200px. When clicked, the button should smoothly scroll the page back to the top.

**Acceptance Criteria**:

- The button should be hidden by default and appear after the user scrolls 200px down the page.
- Clicking the button triggers a smooth scroll back to the top of the page.

**Technical Details**:

- Style the button using CSS and position it at the bottom-right corner of the page.
- Use JavaScript to track the scroll position and display the button after 200px.
- Ensure smooth scrolling using either `scroll-behavior: smooth;` or a JavaScript animation.
- Use the arrow icon from Figma for the button.

**Comment by Neel-07** [comment]
hello @Alexandrbig1 can this issue be assigned to me

**Comment by Alexandrbig1** [comment]
@Neel-07 hi Neel, yes, assigned. Thank you!

**Comment by Alexandrbig1** [comment]
@Neel-07 check it out your task please, the scroll up button is not appearing when scrolling

**Comment by Neel-07** [comment]
@Alexandrbig1  Let me make the upstream pull, i will look into it, rest assured i will fix  it up  soon

**Comment by Neel-07** [comment]
HELLO @Alexandrbig1  i have raised a new pr, also ensured that it is visible and full functionality, please review and let me know if there are any changes that are required.

**Comment by Alexandrbig1** [comment]
@Neel-07 I accepted your PR. But it's still not working, the button is not visible? Please test next time before you create a PR. Make sure it's work, it's visible, it's react when user scroll to bottom for 200px. Thank you

**Comment by Alexandrbig1** [comment]
@Neel-07 and, please, keep working on a same issue for this task

**Comment by Neel-07** [comment]
@Alexandrbig1 

https://github.com/user-attachments/assets/a739791d-afc6-48c3-87e2-cc12a2d2bc03

the feature is working perfectly fine in my local system, let me go through the codebase main branch if there is any issue i will let you know.

**Comment by Alexandrbig1** [comment]
@Neel-07 nice, I see, that's right, working well.
Here is our project website: https://opencodechicago.github.io/Midwest-Pumpkins
Figure it out why it's working locally but not globally ☺️
Did you install any packages, maybe?

**Comment by Alexandrbig1** [comment]
@Neel-07 test first at your environment, and then if everything is working, create a PR, and work in this issue, that we can track the process and then close it and mark 'Done'. Thank you

**Comment by Neel-07** [comment]
@Alexandrbig1 tested everything, creating a pr now.

**Comment by Alexandrbig1** [comment]
@Neel-07 great work. Might consider of adding except scale on hovering, could be a great from user experience, when the button will fill entirely of accent color while the icon on white, will be more visible and integrated for user
