### ISSUE TITLE
SVG Sprite Creation

### ISSUE THREAD

**Issue by Alexandrbig1** [OpenCodeChicago/Midwest-Pumpkins#50]
**Description**:
Create an SVG sprite containing all project icons to optimize loading and improve performance.

**Acceptance Criteria**:

- All individual SVG icons must be combined into a single SVG sprite.
- The icons should be used via the `<use>` element referencing the sprite.
- The sprite should include all icons used on the site, including those for navigation, social media, and other interface elements.

**Technical Details**:

- Collect all individual SVG files used throughout the site.
- Create one sprite file containing these SVG icons.
- Ensure correct usage of the sprite and proper rendering of each icon in the project.

**Comment by Gauravtb2253** [comment]
I would like to work on this
Please assign it to me

Thank you

**Comment by Alexandrbig1** [comment]
Got it, assigned! Thank you

**Comment by Alexandrbig1** [comment]
@Gauravtb2253 great work Gaurav!
