### ISSUE TITLE
Extra Inner navigation bar present

### ISSUE THREAD

**Issue by DanielDunevant** [OpenCodeChicago/Midwest-Pumpkins#69]
![Screenshot 2024-10-06 080324](https://github.com/user-attachments/assets/42e70f34-d359-4a81-8ba9-3893a0c19dff)

**Comment by blunterdecosta123** [comment]
hi @DanielDunevant I would like to work on this issue also can you assign me this under hacktoberfest

**Comment by DanielDunevant** [comment]
Seems to have been solved
