### ISSUE TITLE
ISSUE #20 placeholders correction

### ISSUE THREAD

**Issue by sp9324** [OpenCodeChicago/Midwest-Pumpkins#82]
<img width="1470" alt="Screenshot 2024-10-09 at 4 48 58 PM" src="https://github.com/user-attachments/assets/55c51dfd-394a-41e4-8c7d-da36f889b28d">
General UI enhancement to correct unpleasant placeholders and text on the landing page.

**Comment by Vikassinghrathor** [comment]
Hi , 

I would like to work on this
Please assign it to me

Thank you

**Comment by Mayuphapale** [comment]
i would like to work on this issue . can you assign this issue to me ??
